"""initial schema

Revision ID: 37aaa47a3508
Revises: 
Create Date: 2026-09-16 14:43:16.805956
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '37aaa47a3508'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('actor_name', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('external_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=True),
    sa.Column('khasra_number', sa.String(length=64), nullable=True),
    sa.Column('survey_number', sa.String(length=64), nullable=True),
    sa.Column('khata_number', sa.String(length=64), nullable=True),
    sa.Column('owner_name', sa.String(length=256), nullable=True),
    sa.Column('plot_area_sqm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_records_khasra_number'), ['khasra_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_records_survey_number'), ['survey_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_records_village'), ['village'], unique=False)

    op.create_table('field_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('ocr_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_corrections_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_corrections_field_name'), ['field_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'EXTRACTED', 'AUTO_VERIFIED', 'PENDING_REVIEW', 'VERIFIED', 'REJECTED', 'FAILED', name='docstatus'), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('processing_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('diagnostics', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('extracted_fields',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_field_name'), ['field_name'], unique=False)

    op.create_table('land_parcels',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('parcel_number', sa.String(length=64), nullable=True),
    sa.Column('area_text', sa.String(length=64), nullable=True),
    sa.Column('area_value', sa.Float(), nullable=True),
    sa.Column('area_unit', sa.String(length=32), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('land_classification', sa.String(length=64), nullable=True),
    sa.Column('crop', sa.String(length=64), nullable=True),
    sa.Column('owner_name', sa.String(length=256), nullable=True),
    sa.Column('possessor_name', sa.String(length=256), nullable=True),
    sa.Column('father_name', sa.String(length=256), nullable=True),
    sa.Column('share', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('field_confidences', sa.JSON(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('land_parcels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_land_parcels_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_parcels_owner_name'), ['owner_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_parcels_parcel_number'), ['parcel_number'], unique=False)

    op.create_table('land_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('tehsil', sa.String(length=64), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=True),
    sa.Column('survey_number', sa.String(length=64), nullable=True),
    sa.Column('khasra_number', sa.String(length=64), nullable=True),
    sa.Column('khata_number', sa.String(length=64), nullable=True),
    sa.Column('plot_area_value', sa.Float(), nullable=True),
    sa.Column('plot_area_unit', sa.String(length=16), nullable=True),
    sa.Column('plot_area_sqm', sa.Float(), nullable=True),
    sa.Column('land_classification', sa.String(length=64), nullable=True),
    sa.Column('owner_name', sa.String(length=256), nullable=True),
    sa.Column('father_or_husband_name', sa.String(length=256), nullable=True),
    sa.Column('ownership_type', sa.String(length=64), nullable=True),
    sa.Column('mutation_number', sa.String(length=64), nullable=True),
    sa.Column('mutation_date', sa.String(length=32), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('registration_date', sa.String(length=32), nullable=True),
    sa.Column('record_year', sa.String(length=16), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=32), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    with op.batch_alter_table('land_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_land_records_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_khasra_number'), ['khasra_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_khata_number'), ['khata_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_owner_name'), ['owner_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_survey_number'), ['survey_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_village'), ['village'], unique=False)

    op.create_table('validation_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_results_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_results_document_id'))

    op.drop_table('validation_results')
    with op.batch_alter_table('land_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_land_records_village'))
        batch_op.drop_index(batch_op.f('ix_land_records_survey_number'))
        batch_op.drop_index(batch_op.f('ix_land_records_state'))
        batch_op.drop_index(batch_op.f('ix_land_records_owner_name'))
        batch_op.drop_index(batch_op.f('ix_land_records_khata_number'))
        batch_op.drop_index(batch_op.f('ix_land_records_khasra_number'))
        batch_op.drop_index(batch_op.f('ix_land_records_district'))

    op.drop_table('land_records')
    with op.batch_alter_table('land_parcels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_land_parcels_parcel_number'))
        batch_op.drop_index(batch_op.f('ix_land_parcels_owner_name'))
        batch_op.drop_index(batch_op.f('ix_land_parcels_document_id'))

    op.drop_table('land_parcels')
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_field_name'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_document_id'))

    op.drop_table('extracted_fields')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))

    op.drop_table('documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('field_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_corrections_field_name'))
        batch_op.drop_index(batch_op.f('ix_field_corrections_document_id'))

    op.drop_table('field_corrections')
    with op.batch_alter_table('external_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_records_village'))
        batch_op.drop_index(batch_op.f('ix_external_records_survey_number'))
        batch_op.drop_index(batch_op.f('ix_external_records_khasra_number'))

    op.drop_table('external_records')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
